name: Build and Deploy testCP FrontEnd

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_deploy_testsite:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'

      - name: Install dependencies
        run: npm install

      - name: Use production config
        # копируем prodconfig.json поверх config.json перед сборкой
        run: |
          cp src/config/prodconfig.json src/config/config.json

      - name: Build frontend
        run: npm run build

      - name: Ensure remote directories exist
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            mkdir -p /root/nahon_project/testsite/frontend/cp-dist

      - name: Copy dist via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "dist/*"
          target: "/root/nahon_project/testsite/frontend/cp-dist"
          rm: true
          strip_components: 1
